# syntax=docker/dockerfile:1.7

FROM node:22.12.0-bookworm-slim
WORKDIR /workspace/frontend

COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm npm ci
COPY index.html vite.config.js ./
COPY public public
COPY src src

EXPOSE 5174
CMD ["npm", "run", "dev"]
